import{a as d,S as P,i}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const M="56487481-0495141e7e76f8d02370d655c";d.defaults.baseURL="https://pixabay.com/api/";async function u(r,t){const a={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await d.get("",{params:a})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more-btn"),E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:n,comments:v,downloads:q})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${o}</span></p>
        <p class="info-item"><b>Views</b><span>${n}</span></p>
        <p class="info-item"><b>Comments</b><span>${v}</span></p>
        <p class="info-item"><b>Downloads</b><span>${q}</span></p>
      </div>
    </li>`).join("");p.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){p.innerHTML=""}function g(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function b(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}const w=document.querySelector(".search-form"),B=document.querySelector(".load-more-btn");let l="",c=1;const S=15;w.addEventListener("submit",R);B.addEventListener("click",O);async function R(r){if(r.preventDefault(),l=r.currentTarget.elements.searchQuery.value.trim(),c=1,l===""){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}$(),L(),g();try{const t=await u(l,c);if(t.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),t.totalHits>S&&b()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y(),w.reset()}}async function O(){c+=1,L(),g();try{const r=await u(l,c);h(r.hits),H();const t=Math.ceil(r.totalHits/S);c>=t?i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b()}catch{i.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{y()}}function H(){const r=document.querySelector(".gallery-item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
