import{a as p,S as q,i as a}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="56487481-0495141e7e76f8d02370d655c";p.defaults.baseURL="https://pixabay.com/api/";async function f(r,t){const s={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await p.get("",{params:s})).data}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more-btn"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:c,comments:v,downloads:P})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${o}</span></p>
        <p class="info-item"><b>Views</b><span>${c}</span></p>
        <p class="info-item"><b>Comments</b><span>${v}</span></p>
        <p class="info-item"><b>Downloads</b><span>${P}</span></p>
      </div>
    </li>`).join("");h.insertAdjacentHTML("beforeend",t),E.refresh()}function R(){h.innerHTML=""}function b(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function u(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const w=document.querySelector(".form"),$=document.querySelector(".load-more-btn");let l="",n=1;const S=15;w.addEventListener("submit",B);$.addEventListener("click",O);async function B(r){if(r.preventDefault(),l=r.currentTarget.elements.searchQuery.value.trim(),n=1,l===""){a.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}R(),d(),b();try{const t=await f(l,n);if(t.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits);const s=Math.ceil(t.totalHits/S);n>=s?(d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):u()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),w.reset()}}async function O(){n+=1,d(),b();try{const r=await f(l,n);y(r.hits),H();const t=Math.ceil(r.totalHits/S);n>=t?(d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):u()}catch{a.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"}),u()}finally{L()}}function H(){const r=document.querySelector(".gallery-item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
